table App_Campus_Secciones_Agrupadas
	lineageTag: 9f007c9a-8058-411b-bb35-11f33c6ca4c2

	column Año
		dataType: int64
		formatString: 0
		lineageTag: c4205654-b8a9-4302-a757-dcea26d9c97b
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 9e20e786-7f6e-4967-80fc-bfce731702c3
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Tipo Epoca'
		dataType: string
		lineageTag: 2adbc011-b8c0-4763-aff3-d9bf362947e9
		summarizeBy: none
		sourceColumn: Tipo Epoca

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: int64
		formatString: 0
		lineageTag: 7b903cd3-c80d-4157-a3e0-74ad516e8a12
		summarizeBy: sum
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column Visualizaciones
		dataType: int64
		formatString: 0
		lineageTag: b54907b6-06a0-460c-af1f-f8c5a0224e82
		summarizeBy: sum
		sourceColumn: Visualizaciones

		annotation SummarizationSetBy = Automatic

	column 'Visualizaciones Únicas'
		dataType: int64
		formatString: 0
		lineageTag: 111d368c-e438-403a-b00d-80e8b4f6a78f
		summarizeBy: sum
		sourceColumn: Visualizaciones Únicas

		annotation SummarizationSetBy = Automatic

	column Seccion
		dataType: string
		lineageTag: 9a7d29d7-f5ef-4e22-b854-decfa6e6289b
		summarizeBy: none
		sourceColumn: Seccion

		annotation SummarizationSetBy = Automatic

	column 'Categoria Seccion'
		dataType: string
		lineageTag: c8147b8b-0bdf-4e35-9741-2ac91cca067f
		summarizeBy: none
		sourceColumn: Categoria Seccion

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 2b4e4ad1-ce50-4ebd-9623-7ec42e736478
		summarizeBy: sum
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	partition App_Campus_Secciones_Agrupadas = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/ATS_CI_Proyectos_PRO", "APP_Campus_CI", [Query="EVALUATE App_Campus_Secciones_Agregadas_Anual", Implementation="2.0"]),
				    #"Renamed Columns1" = Table.RenameColumns(Source,{{"App_Campus_Secciones_Agregadas_Anual[Seccion]", "Seccion"}, {"App_Campus_Secciones_Agregadas_Anual[Categoria Seccion]", "Categoria Seccion"}, {"App_Campus_Secciones_Agregadas_Anual[Año]", "Año"}, {"App_Campus_Secciones_Agregadas_Anual[Tipo Epoca]", "Tipo Epoca"}, {"App_Campus_Secciones_Agregadas_Anual[Semestre]", "Semestre"}, {"App_Campus_Secciones_Agregadas_Anual[Mes]", "Mes"}, {"App_Campus_Secciones_Agregadas_Anual[Visualizaciones]", "Visualizaciones"}, {"App_Campus_Secciones_Agregadas_Anual[Visualizaciones Únicas]", "Visualizaciones Únicas"}}),
				    #"Consulta anexada" = Table.Combine({#"Renamed Columns1", App_Campus_Secciones_Agrupadas_Semestral, App_Campus_Secciones_Agrupadas_Mensual}),
				    #"Filas ordenadas" = Table.Sort(#"Consulta anexada",{{"Visualizaciones", Order.Ascending}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Filas ordenadas", "Índice", 1, 1, Int64.Type)
				in
				    #"Índice agregado"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

