table App_Campus_Secciones_Agrupadas_Mensual
	isHidden
	lineageTag: b5580a6e-d723-4fcd-9c78-1f65b963f18b

	column Seccion
		dataType: string
		isHidden
		lineageTag: 9b6a149a-835c-45fb-97a5-54b5871aee29
		summarizeBy: none
		sourceColumn: Seccion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Categoria Seccion'
		dataType: string
		isHidden
		lineageTag: d31a1c9a-78f0-4688-a361-d69eb0e83b85
		summarizeBy: none
		sourceColumn: Categoria Seccion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3bf60416-cff1-42de-a58a-34c799b39963
		summarizeBy: sum
		sourceColumn: Año

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3f423a29-4de2-4b3c-b268-ea188e11dc29
		summarizeBy: sum
		sourceColumn: Mes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 827736c5-3bd9-4fba-8887-675daeec049b
		summarizeBy: sum
		sourceColumn: Semestre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tipo Epoca'
		dataType: string
		isHidden
		lineageTag: 71241a52-1068-44db-a056-1ceb5098e509
		summarizeBy: none
		sourceColumn: Tipo Epoca

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Visualizaciones
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fdb7eec8-0b41-450f-87cf-df298b88fcb0
		summarizeBy: sum
		sourceColumn: Visualizaciones

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visualizaciones Únicas'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 094d4937-3d31-49b0-b498-1ba4b8bd5dbb
		summarizeBy: sum
		sourceColumn: Visualizaciones Únicas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition App_Campus_Secciones_Agrupadas_Mensual = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/ATS_CI_Proyectos_PRO", "APP_Campus_CI", [Query="EVALUATE App_Campus_Secciones_Agregadas_Mensual", Implementation="2.0"]),
				    #"Renamed Columns1" = Table.RenameColumns(Source,{{"App_Campus_Secciones_Agregadas_Mensual[Seccion]", "Seccion"}, {"App_Campus_Secciones_Agregadas_Mensual[Categoria Seccion]", "Categoria Seccion"}, {"App_Campus_Secciones_Agregadas_Mensual[Año]", "Año"}, {"App_Campus_Secciones_Agregadas_Mensual[Tipo Epoca]", "Tipo Epoca"}, {"App_Campus_Secciones_Agregadas_Mensual[Semestre]", "Semestre"}, {"App_Campus_Secciones_Agregadas_Mensual[Mes]", "Mes"}, {"App_Campus_Secciones_Agregadas_Mensual[Visualizaciones]", "Visualizaciones"}, {"App_Campus_Secciones_Agregadas_Mensual[Visualizaciones Únicas]]", "Visualizaciones Únicas"}})
				in
				    #"Renamed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

