table App_Campus_Secciones_Agrupadas_Semestral
	isHidden
	lineageTag: 2b62f095-9a97-4203-aead-d702512813d7

	column Seccion
		dataType: string
		isHidden
		lineageTag: 0356bc2e-eb47-4951-94b0-9336af792847
		summarizeBy: none
		sourceColumn: Seccion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Categoria Seccion'
		dataType: string
		isHidden
		lineageTag: ce87a8eb-1e93-464e-ae19-65fb77d1a325
		summarizeBy: none
		sourceColumn: Categoria Seccion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 58368498-1afe-4d43-a2bc-1060f7fd0d6e
		summarizeBy: sum
		sourceColumn: Año

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 88ad58f0-285a-440c-8aa1-1a1a1e74421e
		summarizeBy: sum
		sourceColumn: Semestre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ca51deca-13fe-4ab1-abb1-6012a172f0a3
		summarizeBy: sum
		sourceColumn: Mes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Tipo Epoca'
		dataType: string
		isHidden
		lineageTag: 85974241-4830-439d-b085-7d9ac2e20744
		summarizeBy: none
		sourceColumn: Tipo Epoca

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Visualizaciones
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 08d0f2f6-1ed8-486f-a339-3aab1e8f800d
		summarizeBy: sum
		sourceColumn: Visualizaciones

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visualizaciones Únicas'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f4b8b98e-067d-4e70-ae47-638603cf4028
		summarizeBy: sum
		sourceColumn: Visualizaciones Únicas

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition App_Campus_Secciones_Agrupadas_Semestral = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/ATS_CI_Proyectos_PRO", "APP_Campus_CI", [Query="EVALUATE UNION(App_Campus_Secciones_Agregadas_Semestral1, App_Campus_Secciones_Agregadas_Semestral2)", Implementation="2.0"]),
				    #"Renamed Columns1" = Table.RenameColumns(Source,{{"App_Campus_Secciones_Agregadas_Semestral1[Seccion]", "Seccion"}, {"App_Campus_Secciones_Agregadas_Semestral1[Categoria Seccion]", "Categoria Seccion"}, {"App_Campus_Secciones_Agregadas_Semestral1[Año]", "Año"}, {"App_Campus_Secciones_Agregadas_Semestral1[Tipo Epoca]", "Tipo Epoca"}, {"App_Campus_Secciones_Agregadas_Semestral1[Semestre]", "Semestre"}, {"App_Campus_Secciones_Agregadas_Semestral1[Mes]", "Mes"}, {"App_Campus_Secciones_Agregadas_Semestral1[Visualizaciones]", "Visualizaciones"}, {"App_Campus_Secciones_Agregadas_Semestral1[Visualizaciones Únicas]", "Visualizaciones Únicas"}})
				in
				    #"Renamed Columns1"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

