table App_Campus_Accesos_Hecho
	lineageTag: 4d9606d1-6637-4307-ab8a-fc6d10709bf8

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 81bdf2b5-ac53-429b-ada4-b3bd447beced
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column 'Tipo Epoca'
		dataType: string
		lineageTag: e4bea187-ec2d-4765-b78e-0a6cf6834263
		summarizeBy: none
		sourceColumn: Tipo Epoca

		annotation SummarizationSetBy = Automatic

	column Semestre
		dataType: int64
		formatString: 0
		lineageTag: a8c6c6e4-cee7-4185-9458-562590d762bd
		summarizeBy: sum
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: dc22addd-c41d-44a2-aef0-b571b33c4fa5
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'usuarios potenciales'
		dataType: int64
		formatString: 0
		lineageTag: 411fe6a7-4630-4f18-8546-dd662f33436d
		summarizeBy: sum
		sourceColumn: usuarios potenciales

		annotation SummarizationSetBy = Automatic

	column 'accesos unicos'
		dataType: int64
		formatString: 0
		lineageTag: 742cb509-8c28-47bd-9002-2587c1f58715
		summarizeBy: sum
		sourceColumn: accesos unicos

		annotation SummarizationSetBy = Automatic

	column 'accesos totales'
		dataType: int64
		formatString: 0
		lineageTag: 757c1c8d-b696-4b76-a7e2-d0b6e4c09ddd
		summarizeBy: sum
		sourceColumn: accesos totales

		annotation SummarizationSetBy = Automatic

	partition App_Campus_Accesos_Hecho = m
		mode: import
		source =
				let
				    Source = AnalysisServices.Database("powerbi://api.powerbi.com/v1.0/myorg/ATS_CI_Proyectos_PRO", "APP_Campus_CI", [Query="EVALUATE#(lf)#(lf)VAR union_table = #(lf)#(tab)UNION (#(lf)        SELECTCOLUMNS (#(lf)            App_Campus_Accesos_Hecho_Anual,#(lf)            ""Año"", [Año],#(lf)            ""Tipo Epoca"", [Tipo Epoca],#(lf)            ""Semestre"", [Semestre],#(lf)            ""Mes"", [Mes],#(lf)            ""usuarios potenciales"", [usuarios potenciales],#(lf)            ""accesos unicos"", [accesos unicos],#(lf)            ""accesos totales"", [accesos totales]#(lf)        ),#(lf)        SELECTCOLUMNS (#(lf)            App_Campus_Accesos_Hecho_Semestral,#(lf)            ""Año"", [Año],#(lf)            ""Tipo Epoca"", [Tipo Epoca],#(lf)            ""Semestre"", [Semestre],#(lf)            ""Mes"", [Mes],#(lf)            ""usuarios potenciales"", [usuarios potenciales],#(lf)            ""accesos unicos"", [accesos unicos],#(lf)            ""accesos totales"", [accesos totales]#(lf)        ),#(lf)        SELECTCOLUMNS (#(lf)            App_Campus_Accesos_Hecho_Mensual,#(lf)            ""Año"", [Año],#(lf)            ""Tipo Epoca"", [Tipo Epoca],#(lf)            ""Semestre"", [Semestre],#(lf)            ""Mes"", [Mes],#(lf)            ""usuarios potenciales"", [usuarios potenciales],#(lf)            ""accesos unicos"", [accesos unicos],#(lf)            ""accesos totales"", [accesos totales]#(lf)        )#(lf)    )#(lf)#(lf)#(lf)RETURN union_table", Implementation="2.0"]),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(Source,{{"[Año]", "Año"}, {"[Tipo Epoca]", "Tipo Epoca"}, {"[Semestre]", "Semestre"}, {"[Mes]", "Mes"}, {"[usuarios potenciales]", "usuarios potenciales"}, {"[accesos unicos]", "accesos unicos"}, {"[accesos totales]", "accesos totales"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

