table Comun
	lineageTag: e7dd2af7-9c52-4486-a087-505ffc89fa59

	measure 'Tipo Epoca' = ```
			
			
			
			var is_year_selected = HASONEVALUE(Date_DIM[Año])
			var is_semester_selected = HASONEVALUE(Date_DIM[Número del Semestre])
			var is_month_selected = HASONEVALUE(Date_DIM[Nombre Mes])
			
			return IF(is_year_selected && NOT is_month_selected && NOT is_semester_selected, "Anual",
			        IF(is_year_selected && is_semester_selected && NOT is_month_selected ,"Semestral", 
			
			        IF(is_year_selected && is_month_selected, "Mensual")))
			
			```
		lineageTag: 7399b1b1-7263-4844-9e8b-bf389172dde8

	measure 'Año Epoca' = ```
			
			var is_year_selected = HASONEVALUE(Date_DIM[Año])
			
			return IF(is_year_selected, CONVERT(SELECTEDVALUE(Date_DIM[Año],0),INTEGER),0)
			
			
			```
		formatString: 0
		lineageTag: dbe599aa-754f-4899-a547-868e5abf8135

	measure 'Sub Epoca numero' = ```
			
			var is_semester_selected = HASONEVALUE(Date_DIM[Número del Semestre])
			var is_month_selected = HASONEVALUE(Date_DIM[Nombre Mes])
			
			return IF(is_semester_selected && NOT is_month_selected ,SELECTEDVALUE(Date_DIM[Número del Semestre], 0), 
			
			        IF(is_month_selected, SELECTEDVALUE(Date_DIM[Número del Mes], 0), 0))
			```
		formatString: 0
		lineageTag: 78a96fb4-b2a8-4abf-8ddc-64f56e53de4c

	measure 'Previous Epoca' = ```
			
			var is_year_selected = HASONEVALUE(Date_DIM[Año])
			var is_semester_selected = HASONEVALUE(Date_DIM[Número del Semestre])
			var is_month_selected = HASONEVALUE(Date_DIM[Nombre Mes])
			var previous_year = SELECTEDVALUE(Date_DIM[Año],0)-1
			
			return IF(is_year_selected && NOT is_month_selected && NOT is_semester_selected, CONVERT(previous_year,STRING),
			        IF(is_year_selected && is_semester_selected && NOT is_month_selected ,previous_year & "S" & SELECTEDVALUE(Date_DIM[Número del Semestre], 0), 
			
			        IF(is_year_selected && is_month_selected, previous_year & "M" & SELECTEDVALUE(Date_DIM[Número del Mes], 0), 0)))
			
			```
		lineageTag: 6f55e818-24a9-4aaa-8fa3-5d422b8ed860

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Mensaje No Data' = "No hay datos"
		lineageTag: bf952a9c-7b66-433f-8444-689548811c67

	measure 'Idioma Filter InteraccionaTV' =
			
			
			
			
			VAR Calculo =
			CALCULATE(
			    DISTINCTCOUNT(Alias_Idioma_DIM[Alias]),
			    FILTER(
			            Alias_Idioma_DIM,
			            Alias_Idioma_DIM[Alias] in Values(InteraccionaTV_Idiomas_Hecho[Cod_idioma])
			    )
			)
			
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: 0
		lineageTag: a8ffe2a8-982e-4783-9102-bab1f767c54c

	measure 'Idioma Filter Emailing' =
			
			
			
			
			VAR Calculo =
			CALCULATE(
			    DISTINCTCOUNT(Alias_Idioma_DIM[Alias]),
			    FILTER(
			            Alias_Idioma_DIM,
			            Alias_Idioma_DIM[Alias] in Values(Campanas_Email_Idioma_Hecho[Cod_idioma])
			    )
			)
			
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: 0
		lineageTag: 29f28f15-d985-4d61-b146-03aa6a3fec44

	partition Comun = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

