table Emailing
	isHidden
	lineageTag: e37f329e-c7db-4b29-9d96-8b89079c9f87

	column Title
		dataType: string
		lineageTag: 6ed5ae40-0bf3-4f51-935a-541bcfc38445
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column ' Topic'
		dataType: string
		isHidden
		lineageTag: f15a9b11-90b5-41b5-97dc-f2a81f39b6c4
		summarizeBy: none
		sourceColumn: " Topic"

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sender Category'
		dataType: string
		isHidden
		lineageTag: c460d032-2356-4990-80dd-dd79ee78dd8a
		summarizeBy: none
		sourceColumn: Sender Category

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Sender
		dataType: string
		isHidden
		lineageTag: 4f0ddc90-4a4d-4c2d-8db3-542c78ca96ab
		summarizeBy: none
		sourceColumn: Sender

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'division / area '
		dataType: string
		isHidden
		lineageTag: 9152212f-bd7e-4b15-be49-665501c64c62
		summarizeBy: none
		sourceColumn: "division / area "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Target group (description)'
		dataType: string
		isHidden
		lineageTag: 13d38e92-b212-4730-abf9-0fe11aef8f6c
		summarizeBy: none
		sourceColumn: Target group (description)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		isHidden
		lineageTag: ded6a63f-e958-4a81-9d09-e391d317a2d1
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Work center'
		dataType: string
		isHidden
		lineageTag: 8c45d987-56c5-42bf-82c0-08ef59b4cb3c
		summarizeBy: none
		sourceColumn: Work center

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		isHidden
		lineageTag: c85dbfa6-97b9-43ed-9297-fbd81ba91712
		summarizeBy: none
		sourceColumn: Role

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Newsletter (yes/no)'
		dataType: string
		isHidden
		lineageTag: 26c2c2b9-6c24-4754-be23-dc5276f79033
		summarizeBy: none
		sourceColumn: Newsletter (yes/no)

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column idioma
		dataType: string
		isHidden
		lineageTag: 45d81412-9fda-469a-8a38-f9c69fafd76a
		summarizeBy: none
		sourceColumn: idioma

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		isHidden
		formatString: General Date
		lineageTag: 8300ffe7-1602-43f7-9cb5-37ba072f2325
		summarizeBy: none
		sourceColumn: fecha

		variation Variation
			isDefault
			relationship: 5f2e253a-cc0c-4f69-9919-f6d84df2d7f1
			defaultHierarchy: LocalDateTable_1d6d3f3f-249d-43d1-bb16-1c891bc1b98a.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column asunto
		dataType: string
		isHidden
		lineageTag: 882756f0-92eb-48b6-a749-76d6b5146006
		summarizeBy: none
		sourceColumn: asunto

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'semana del flash'
		dataType: double
		isHidden
		lineageTag: 53fcb9ee-51cc-45a4-87ed-cdf46a634669
		summarizeBy: sum
		sourceColumn: semana del flash

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Año
		dataType: string
		isHidden
		lineageTag: a9d211d9-d0f4-44bc-a071-57561dab8bf1
		summarizeBy: none
		sourceColumn: Año

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		isHidden
		lineageTag: 6de65203-067a-43ae-9560-1c2bbe67c877
		summarizeBy: none
		sourceColumn: Mes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		isHidden
		lineageTag: 7263ffe4-9f90-46fb-97eb-e7ad107f46b5
		summarizeBy: none
		sourceColumn: Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column id_campaña
		dataType: string
		isHidden
		lineageTag: 0c9f43cc-dd2a-499c-b56d-d408c962be8a
		summarizeBy: none
		sourceColumn: id_campaña

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Destinatarios
		dataType: double
		isHidden
		lineageTag: 63bab44a-a690-406a-8079-69a296016037
		summarizeBy: sum
		sourceColumn: Destinatarios

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Recibidos
		dataType: double
		isHidden
		lineageTag: c6d299c9-621a-4614-be82-7a95e565de2d
		summarizeBy: sum
		sourceColumn: Recibidos

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aperturas '
		dataType: double
		isHidden
		lineageTag: ed1f3959-65c0-42cf-bc69-d3c673f58794
		summarizeBy: sum
		sourceColumn: "Aperturas "

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Abridores
		dataType: double
		isHidden
		lineageTag: 944a9a4d-9167-44d0-b32e-b2c96e1129df
		summarizeBy: sum
		sourceColumn: Abridores

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Clicks
		dataType: double
		isHidden
		lineageTag: 43008cf5-c2ea-4c49-a49f-0968bc060442
		summarizeBy: sum
		sourceColumn: Clicks

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c611a630-0700-4e97-a966-cc620b0cc7a5
		summarizeBy: count
		sourceColumn: ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ratio efectividad'
		dataType: double
		isHidden
		lineageTag: a75fc460-e9a9-4439-aa4b-db852aea2dbd
		summarizeBy: sum
		sourceColumn: ratio efectividad

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Emailing = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://acciona365.sharepoint.com/sites/ats_ci_proyectos_pro/", [Implementation="2.0", ViewMode="All"]),
				    #"7da917a5-0425-497d-ac4a-f5ae91316d3a" = Source{[Id="7da917a5-0425-497d-ac4a-f5ae91316d3a"]}[Items],
				    #"Removed Columns" = Table.RemoveColumns(#"7da917a5-0425-497d-ac4a-f5ae91316d3a",{"Color Tag", "Compliance Asset Id", "Content Type", "Modified", "Created", "Created By", "Modified By", "Version", "Attachments", "Edit", "DocIcon", "Item Child Count", "Folder Child Count", "Label setting", "Retention label", "Retention label Applied", "Label applied by", "Item is a Record", "App Created By", "App Modified By"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "ratio efectividad2", each [Abridores]/ [Recibidos]),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"ratio efectividad"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"ratio efectividad2", "ratio efectividad"}, {"nombre campaña", "Title"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"ratio efectividad", type number}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

