table Encuestas_Hecho
	lineageTag: 04a918d2-16bd-49d5-8d09-ef6734ef63b4

	column INVITADOS
		dataType: int64
		formatString: #,0
		lineageTag: ca1b23d9-695a-4106-a94d-5771dad14f8f
		summarizeBy: sum
		sourceColumn: INVITADOS

		annotation SummarizationSetBy = Automatic

	column COLECTIVO
		dataType: string
		lineageTag: 3e1a5a25-7bc9-401d-86ce-0485a3c1905d
		summarizeBy: none
		sourceColumn: COLECTIVO

		annotation SummarizationSetBy = Automatic

	column 'Nº RESPUESTAS'
		dataType: int64
		formatString: #,0
		lineageTag: 048dd954-35dc-49ca-a1a4-a72e0ee6814e
		summarizeBy: sum
		sourceColumn: Nº RESPUESTAS

		annotation SummarizationSetBy = Automatic

	column %
		dataType: double
		lineageTag: 1c1cf5ca-ea5f-40b6-bc52-b0edfb00f9e5
		summarizeBy: sum
		sourceColumn: %

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column encuesta_id
		dataType: int64
		formatString: 0
		lineageTag: f020ae21-4d84-41e7-8426-832eafc14671
		summarizeBy: none
		sourceColumn: encuesta_id

		annotation SummarizationSetBy = Automatic

	column encuesta_hecho_id
		dataType: int64
		formatString: 0
		lineageTag: 14fe5fa4-0413-40d6-b075-8e420c37eb54
		summarizeBy: sum
		sourceColumn: encuesta_hecho_id

		annotation SummarizationSetBy = Automatic

	column Lanzamiento
		dataType: dateTime
		formatString: Short Date
		lineageTag: fd42c980-a133-4f18-8417-e312e338ec17
		summarizeBy: none
		sourceColumn: Lanzamiento

		variation Variation
			isDefault
			relationship: 7210f811-d0b2-4d0d-961e-ffab95d0510c
			defaultHierarchy: LocalDateTable_fad2489e-70b1-4591-998b-f73f4c90471b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Cierre
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2a15d9b2-05ef-48a4-824e-7e5ee966324a
		summarizeBy: none
		sourceColumn: Cierre

		variation Variation
			isDefault
			relationship: 267cb5d4-97d2-4fd8-a4d9-4f5b319c96fb
			defaultHierarchy: LocalDateTable_dc177612-f090-4074-9b9e-8950e1fc60da.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column filename
		dataType: string
		lineageTag: 303c3dc2-9245-4cd9-ae98-8191311030e1
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	partition Encuestas_Hecho = m
		mode: import
		source =
				let
				    Source = Sql.Database("QECCDWH.acciona.int,60001", "DATA_DW"),
				    KPIS_Encuestas_Hecho = Source{[Schema="KPIS",Item="Encuestas_Hecho"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(KPIS_Encuestas_Hecho,{{"LANZAMIENTO", "Lanzamiento"}, {"CIERRE", "Cierre"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

