table Eventos_hecho
	lineageTag: 1cf12586-0cfb-4e2c-b7f0-fdef65372a66

	column evento_hecho_id
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: de2043a7-a67d-4ba9-b89c-fd0a2d95bdc7
		summarizeBy: none
		sourceColumn: evento_hecho_id

		annotation SummarizationSetBy = User

	column FECHA
		dataType: dateTime
		formatString: Short Date
		sourceProviderType: date
		lineageTag: 7f443b7e-a70b-44aa-9d86-2b6c22c94747
		summarizeBy: none
		sourceColumn: FECHA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nombre evento'
		dataType: string
		sourceProviderType: nvarchar(500)
		lineageTag: 4c2bab38-4d44-486d-ab1c-bb6a6b34a714
		summarizeBy: none
		sourceColumn: Nombre evento

		annotation SummarizationSetBy = Automatic

	column 'VISUALIZACIONES UNICAS'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: af0cecdd-427d-4495-8953-37c72bc3de0c
		summarizeBy: sum
		sourceColumn: VISUALIZACIONES UNICAS

		annotation SummarizationSetBy = Automatic

	column PAISES
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: dbff66e1-f0aa-4081-9176-cdf923483ed2
		summarizeBy: sum
		sourceColumn: PAISES

		annotation SummarizationSetBy = Automatic

	column 'Duración evento'
		dataType: dateTime
		formatString: h:nn
		sourceProviderType: time
		lineageTag: ae32143d-873c-4c65-916e-03865b7236ac
		summarizeBy: none
		sourceColumn: Duración evento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Asistentes presenciales'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 457a3b95-4d7f-448c-a3fe-e38856c8d7fa
		summarizeBy: sum
		sourceColumn: Asistentes presenciales

		annotation SummarizationSetBy = Automatic

	column idioma
		dataType: string
		sourceProviderType: nvarchar(500)
		lineageTag: 936f172f-b741-427b-822b-3cfed79aa286
		summarizeBy: none
		sourceColumn: idioma

		annotation SummarizationSetBy = Automatic

	column 'Ubicación y modalidad'
		dataType: string
		sourceProviderType: nvarchar(500)
		lineageTag: 1592a2c3-6be6-4eec-b296-c9231ea22278
		summarizeBy: none
		sourceColumn: Ubicación y modalidad

		annotation SummarizationSetBy = Automatic

	column 'tipo evento'
		dataType: string
		sourceProviderType: nvarchar(500)
		lineageTag: 8726653e-dcd1-4b90-bafd-3a1eddc6b4be
		summarizeBy: none
		sourceColumn: tipo evento

		annotation SummarizationSetBy = Automatic

	column 'señales Teams'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: dcb7e8a6-57e4-4b4d-a1c0-7e9c64a57f9f
		summarizeBy: sum
		sourceColumn: señales Teams

		annotation SummarizationSetBy = Automatic

	column filename
		dataType: string
		sourceProviderType: nvarchar(500)
		lineageTag: 47441ac7-4aaa-4b5b-98f0-870a73f479fe
		summarizeBy: none
		sourceColumn: filename

		annotation SummarizationSetBy = Automatic

	column VisualizacionesUnicas0 = IF(ISBLANK(Eventos_hecho[VISUALIZACIONES UNICAS]),0,Eventos_hecho[VISUALIZACIONES UNICAS])
		formatString: 0
		lineageTag: cad6df96-7c23-4249-a908-5d56e02377b1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Eventos_hecho = m
		mode: import
		source =
				let
				    Source = Sql.Database("QECCDWH.acciona.int,60001", "DATA_DW"),
				    KPIS_Eventos_hecho = Source{[Schema="KPIS",Item="Eventos_hecho"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(KPIS_Eventos_hecho,{{"VISUALIZACIONES UNICAS ONLINE", "VISUALIZACIONES UNICAS"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

