table Interacciona_Visitas_Seccion_Pais_Hecho
	lineageTag: f7fd2e1a-f293-44b0-85bf-611254bdfd3b

	column Views
		dataType: int64
		formatString: 0
		lineageTag: 68fed23a-7143-4dff-8b8c-b9190cb1916f
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	column 'Unique Users'
		dataType: int64
		formatString: 0
		lineageTag: d82a301e-458c-45e1-8e39-a33e8958a34b
		summarizeBy: sum
		sourceColumn: Unique Users

		annotation SummarizationSetBy = Automatic

	column Duration
		dataType: dateTime
		formatString: Long Time
		lineageTag: 703e2d4d-2f1f-4cda-8863-e1c77026ba5d
		summarizeBy: none
		sourceColumn: Duration

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Exit Rate'
		dataType: double
		lineageTag: a53f048c-19f4-444e-8630-32ef90d965c5
		summarizeBy: sum
		sourceColumn: Exit Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column seccion_id
		dataType: string
		lineageTag: 6e1b4150-fe9b-4fd5-b7d8-78b8216ab9bf
		summarizeBy: none
		sourceColumn: seccion_id

		annotation SummarizationSetBy = Automatic

	column pais_id
		dataType: string
		lineageTag: 417831cf-000a-45e8-af84-9d1d4329a6ff
		summarizeBy: none
		sourceColumn: pais_id

		annotation SummarizationSetBy = Automatic

	column 'Tipo Epoca'
		dataType: string
		lineageTag: 3decd598-0e73-4551-bf52-5d45b719a116
		summarizeBy: none
		sourceColumn: Tipo Epoca

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: int64
		formatString: 0
		lineageTag: a42aa4de-e23c-4565-8a96-6928247e96c4
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = User

	column Semestre
		dataType: int64
		formatString: 0
		lineageTag: 3faa56fb-3bb2-4432-b1a3-d0b8930ffe1e
		summarizeBy: sum
		sourceColumn: Semestre

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 5897d8d0-4426-4502-b7bf-7233c986aa7b
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: f246d8b0-c5c5-4a42-8d06-c73b2a9c8587
		summarizeBy: sum
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Interacciona_Visitas_Seccion_Pais_Hecho = m
		mode: import
		source =
				let
				    Source = Sql.Database("QECCDWH.acciona.int,60001", "DATA_DW"),
				    #"Duplicated Column" = Source{[Schema="KPIS",Item="Interacciona_Visitas_Seccion_Paises_Hecho"]}[Data],
				    #"Added Index" = Table.AddIndexColumn(#"Duplicated Column", "Index", 0, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

