table Maestro_Codigos_Pestañas_Categorías
	lineageTag: d4927483-97cd-422a-8b4d-4e77d328d708

	column Orden_Categoria
		dataType: int64
		formatString: 0
		lineageTag: 92804958-734c-4543-ac0b-3f99be2d2057
		summarizeBy: sum
		sourceColumn: Orden_Categoria

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: b933ccb3-fa5b-46ba-a1f2-b3226f2d0aff
		summarizeBy: none
		sourceColumn: Categoria
		sortByColumn: Orden_Categoria

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Categoria_EN
		dataType: string
		lineageTag: e29136c7-ad1f-430e-bcf9-54bf4c4596bd
		summarizeBy: none
		sourceColumn: Categoria_EN
		sortByColumn: Orden_Categoria

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition Maestro_Codigos_Pestañas_Categorías = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZY29CsMwDIRfxXjO0v+5Q4cOpYGELsaDcEUxNHKw5ELePrYDhaaT7rs7dMbojW50lwaIPiwqy0nbxuht5gu5hCzANYsfnLhmu8xXEozgnA8E/ePfKL19+TGAf39vcQ+Z2kQSWD1R1Q2SWPZviOLppdrgSZap4+rzGkvnlM27RGB1Hkf+BWtn", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Orden_Categoria = _t, Categoria = _t, Categoria_EN = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Orden_Categoria", Int64.Type}, {"Categoria", type text}, {"Categoria_EN", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

