table medidas_apps
	lineageTag: fa58ba8f-73a1-49e2-bfcf-d3c8307bbb45

	measure 'Usuarios Potenciales App' = ```
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[usuarios potenciales]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 0547b24a-1847-4e83-8391-a52c6d10107f

	measure 'Usuarios Unicos App' = ```
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[accesos unicos]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: a2748728-f5ff-4d7c-bcde-8df6e49c33f3

	measure 'Visualizaciones Totales App' = ```
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[accesos totales]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: e7a92501-690f-4f1f-8d13-a65154f0bdb2

	measure 'Tasa Acceso App' = ```
			
			
			medidas_apps[Usuarios Unicos App]/medidas_apps[Usuarios Potenciales App]
			
			```
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 0d5ee7f5-2a9b-40c8-b539-e3ced79355f8

	measure 'Comparision Usuarios Potenciales Apps' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[usuarios potenciales]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_apps[Usuarios Potenciales App]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 3fd37a45-582d-4457-880a-a2a02ae684e5

	measure 'Comparision Tasa Acceso Apps' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = medidas_apps[LYTD Tasa Acceso App]
			
			--VAR numerator = medidas_apps[Tasa Acceso App]
			Var numerator = 1
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 92c516b5-40af-45b1-a6b7-a320a2ee5b7a

	measure 'Comparision Visualizaciones Totales Apps' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[accesos totales]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_apps[Visualizaciones Totales App]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: ea944cd5-ba6f-4445-b489-c10ae22bdd33

	measure 'Comparision Usuarios Unicos Apps' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[accesos unicos]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_apps[Usuarios Unicos App]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 7e7ce063-64d0-44b0-8ecf-d42f577c6f4f

	measure 'Push Noticias' = ```
			
			 COUNTROWS(FILTER(APP_Campus_Comunicaciones, APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia" && APP_Campus_Comunicaciones[flg_habilitar_notificacionespush] = TRUE()))
			
			
			```
		formatString: #,0
		lineageTag: 082db173-ef7f-47a5-8e55-28634a3e33a6

	measure 'Push Avisos' = ```
			
			 COUNTROWS(FILTER(APP_Campus_Comunicaciones, APP_Campus_Comunicaciones[tipo_comunicacion] = "Aviso" && APP_Campus_Comunicaciones[flg_habilitar_notificacionespush] = TRUE()))
			
			```
		formatString: #,0
		lineageTag: 45ceff5a-4c38-490a-927b-c7e966ba1efe

	measure 'Comparision Noticias Pushed Apps' = ```
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			
			var denominator =
			    CALCULATE(
			
			    count(APP_Campus_Comunicaciones[de_titulo]),
			    APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia",
			    APP_Campus_Comunicaciones[flg_habilitar_notificacionespush] = TRUE(),
			    filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min)
			
			    
			)
			
			VAR numerator = medidas_apps[Push Noticias]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
			```
		lineageTag: 6c2ecb71-c656-42a5-b286-d90e2e3b41d9

	measure 'Comparision Avisos Pushed Apps' =
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			var denominator =
			    CALCULATE(
			
			    count(APP_Campus_Comunicaciones[de_titulo]),
			    APP_Campus_Comunicaciones[tipo_comunicacion] = "Aviso",
			    APP_Campus_Comunicaciones[flg_habilitar_notificacionespush] = TRUE(),
			    filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min)
			)
			
			VAR numerator = medidas_apps[Push Avisos]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: acf6be58-4f7c-4e14-8dd9-7517122e2de8

	measure 'Comparision Noticias Publicadas Apps' =
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			VAR denominator = medidas_apps[LYTD Noticias Publicadas Apps]
			
			VAR numerator = medidas_apps[Noticias App Publicadas]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 40585bad-3d8a-44d6-a3b0-cab46df46fec

	measure 'LYTD Noticias Publicadas Apps' = ```
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			
			RETURN CALCULATE(
			
			    count(APP_Campus_Comunicaciones[de_titulo]),
			    APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia",
			    filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min)
			    // FILTER(
			    //     APP_Campus_Comunicaciones,
			    //     APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia"
			    // )
			)
			
			```
		formatString: #,0
		lineageTag: 734d3027-15b8-4192-97c5-93fd87ec8d77

	measure 'LYTD Avisos Publicadas Apps' = ```
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			RETURN CALCULATE(
			
			    count(APP_Campus_Comunicaciones[de_titulo]),
			    APP_Campus_Comunicaciones[tipo_comunicacion] = "Aviso",
			    filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min)
			    
			)
			
			
			```
		formatString: #,0
		lineageTag: 89519e85-c19a-4e5e-8e60-5685730ec3a0

	measure 'Comparision Avisos Publicadas Apps' =
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			VAR denominator = medidas_apps[LYTD Avisos Publicadas Apps]
			
			VAR numerator = medidas_apps[Avisos App Publicadas]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 39d6e4ea-66e5-4987-9b1e-4dce08f01aa6

	measure 'LYTD Visitas Avisos Apps' =
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			RETURN CALCULATE(
			
			    SUM(APP_Campus_Comunicaciones[Nº Total Visualizaciones]),
			    APP_Campus_Comunicaciones[tipo_comunicacion] = "Aviso",
			    filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min)
			)
		formatString: #,0
		lineageTag: f54ac0da-8ac0-4ab6-a0cf-03ece6b2f27e

	measure 'LYTD Visitas Noticias Apps' =
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			RETURN CALCULATE(
			
			    SUM(APP_Campus_Comunicaciones[Nº Total Visualizaciones]),
			    APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia",
			    filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min)
			)
		formatString: #,0
		lineageTag: 0714c5e8-e3f3-4dd7-b38d-d94047f7adfe

	measure 'Visualizaciones Secciones Noticias App by epoca' = ```
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "News" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: ee91c1f4-c306-4a51-b8eb-952251075402

	measure 'Usuarios Unicos Secciones Noticias App by epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "News" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: adbcdb5a-877c-4834-bb06-804b0d6e8632

	measure 'Tasa Acceso Secciones Noticias App by epoca' = ```
			medidas_apps[Usuarios Unicos Secciones Noticias App by epoca]/medidas_apps[Usuarios Unicos App]
			
			```
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 51d70ca4-c174-476d-9e92-8136e111a25a

	measure 'Visualizaciones Secciones Avisos App by epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "Notifications" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: caf2829a-179f-4e3f-ae93-3d8c831e0a03

	measure 'Usuarios Unicos Secciones Avisos App by epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "Notifications" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: fe1a5ddb-b3cc-48e4-89d6-426f7d3ab5c2

	measure 'Tasa Acceso Secciones Avisos App by epoca' = medidas_apps[Usuarios Unicos Secciones Avisos App by epoca]/medidas_apps[Usuarios Unicos App]
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 28929b26-daf7-4c34-b42f-af3c1433ddc1

	measure 'Comparision Usuarios Unicos Secciones Noticias App by epoca' =
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			var lytd_usuarios=
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "News" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			VAR numerator = medidas_apps[Usuarios Unicos Secciones Noticias App by epoca]
			VAR difference = IF(ISBLANK(lytd_usuarios)|| lytd_usuarios = 0, "NaN", DIVIDE(numerator, lytd_usuarios) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 110ae6f5-44d7-40d9-9221-b2a3e4cb9679

	measure 'Comparision Visualizaciones Secciones Noticias App by epoca' =
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			var lytd_usuarios=
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "News" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			VAR numerator = medidas_apps[Visualizaciones Secciones Avisos App by epoca]
			VAR difference = IF(ISBLANK(lytd_usuarios)|| lytd_usuarios = 0, "NaN", DIVIDE(numerator, lytd_usuarios) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: ef3cb66a-7de6-40cf-bfc0-a6a1d460335d

	measure 'Comparision Usuarios Unicos Secciones Avisos App by epoca' =
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			 var lytd_usuarios=
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "Notifications" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			VAR numerator = medidas_apps[Usuarios Unicos Secciones Noticias App by epoca]
			VAR difference = IF(ISBLANK(lytd_usuarios)|| lytd_usuarios = 0, "NaN", DIVIDE(numerator, lytd_usuarios) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 4ee1d790-305e-437e-b146-9403ebabac01

	measure 'Comparision Visualizaciones Secciones Avisos App by epoca' =
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			var lytd_usuarios=
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "Notifications" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			VAR numerator = medidas_apps[Visualizaciones Secciones Avisos App by epoca]
			VAR difference = IF(ISBLANK(lytd_usuarios)|| lytd_usuarios = 0, "NaN", DIVIDE(numerator, lytd_usuarios) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 447861d3-90df-4e08-b633-61dcbc2a109e

	measure 'LYTD Usuarios Unicos Apps' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			return CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[accesos unicos]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
		formatString: #,0
		lineageTag: 18e5952b-da68-42dd-83f4-7a611a2b54b8

	measure 'Comparision Tasa Acceso Secciones Noticias App by epoca' = ```
			
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR usuarios_unicos_lytd = 
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "News" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			 var denominator=
			    CALCULATE(usuarios_unicos_lytd/medidas_apps[LYTD Usuarios Unicos Apps])
			    
			VAR numerator = medidas_apps[Tasa Acceso Secciones Noticias App by epoca]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
			```
		lineageTag: ea7ce7af-c9c4-4ad8-862a-acf8b499cf7b

	measure 'Comparision Tasa Acceso Secciones Avisos App by epoca' =
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR usuarios_unicos_lytd =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Seccion] = "Notifications" &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			 var denominator=
			    CALCULATE(usuarios_unicos_lytd/medidas_apps[LYTD Usuarios Unicos Apps])
			
			VAR numerator = medidas_apps[Tasa Acceso Secciones Avisos App by epoca]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: e00122ee-f60f-4793-8419-a454e70c9c27

	measure 'Noticias App Publicadas' = ```
			
			 COUNTROWS(FILTER(APP_Campus_Comunicaciones, APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia"))
			
			
			
			```
		formatString: #,0
		lineageTag: 306ddce9-e1b1-4b2b-b569-45856a7147a0

	measure 'Avisos App Publicadas' = ```
			
			
			 COUNTROWS(FILTER(APP_Campus_Comunicaciones, APP_Campus_Comunicaciones[tipo_comunicacion] = "Aviso"))
			```
		formatString: #,0
		lineageTag: fb2418ad-f28e-48da-9ebd-a6d807b5efda

	measure 'Noticias App Visualizaciones Totales' = ```
			
			CALCULATE(
			    SUM(APP_Campus_Comunicaciones[Nº Total Visualizaciones]),
			    FILTER(
			        APP_Campus_Comunicaciones,
			        APP_Campus_Comunicaciones[tipo_comunicacion] = "Noticia"
			    )
			)
			
			```
		formatString: #,0
		lineageTag: c035a777-e667-47be-9854-3e7e2d1c0c4a

	measure 'Avisos App Visualizaciones Totales' =
			
			CALCULATE(
			    SUM(APP_Campus_Comunicaciones[Nº Total Visualizaciones]),
			    FILTER(
			        APP_Campus_Comunicaciones,
			        APP_Campus_Comunicaciones[tipo_comunicacion] = "Aviso"
			    )
			)
		formatString: #,0
		lineageTag: ed98f98f-44cf-4c0b-82bb-94d1ff041b53

	measure 'Comparision Visualizaciones Totales Noticias App' =
			
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			 var denominator=
			    medidas_apps[LYTD Visitas Noticias Apps]
			VAR numerator = medidas_apps[Noticias App Visualizaciones Totales]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 56e41a0c-fe1c-491b-99d5-a5efb02aabb0

	measure 'Comparision Visualizaciones Totales Avisos App' =
			
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			 var denominator= medidas_apps[LYTD Visitas Avisos Apps]
			VAR numerator = medidas_apps[Avisos App Visualizaciones Totales]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 33c07b31-fdf2-47a1-af4c-dc8430d058fd

	measure 'Measure Top 20' = ```
			
			
			
			    RANKX(
			        ALLSELECTED(
			        
			        APP_Campus_Comunicaciones[de_categoria_new],
			        APP_Campus_Comunicaciones[de_titulo],
			        APP_Campus_Comunicaciones[flg_habilitar_notificacionespush],
			        APP_Campus_Comunicaciones[fec_publicacion]
			        ),
			
			        Calculate(SUM(APP_Campus_Comunicaciones[Nº Total Visualizaciones]))
			    )
			
			
			
			```
		formatString: 0
		lineageTag: ecc6269e-4003-4a6e-9f95-5966f401ca57

	measure 'Visualizaciones Secciones individuales' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: e0b1def0-a79a-45e6-a0ca-652004212bda

	measure 'Usuarios Secciones individuales' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(App_Campus_Secciones_Agrupadas[Visualizaciones Únicas]),
			    FILTER(
			        'App_Campus_Secciones_Agrupadas',
			        'App_Campus_Secciones_Agrupadas'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Secciones_Agrupadas'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Secciones_Agrupadas'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Secciones_Agrupadas'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: cc38f251-65d5-43b0-8465-acbe7605acbd

	measure 'Tasa Acceso Secciones individuales App by epoca' = medidas_apps[Usuarios Secciones individuales]/medidas_apps[Usuarios Unicos App]
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 0090c147-c25a-4e27-bf87-a2c63dd6566b

	measure 'LYTD Usuarios Potenciales Apps' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			return CALCULATE(
			    SUM(App_Campus_Accesos_Hecho[usuarios potenciales]),
			    FILTER(
			        'App_Campus_Accesos_Hecho',
			        'App_Campus_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'App_Campus_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'App_Campus_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'App_Campus_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
		formatString: 0
		lineageTag: 2dd914ec-754a-40a6-b929-b143036b5410

	measure 'LYTD Tasa Acceso App' =
			
			
			medidas_apps[LYTD Usuarios Unicos Apps]/medidas_apps[LYTD Usuarios Potenciales Apps]
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: e911a08d-8d8e-4f56-b06d-ee7f614bcd4f

	partition medidas_apps = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

