table medidas_Interacciona
	lineageTag: c1edc661-1c11-4a47-88c5-6dfcf526230a

	measure 'Usuarios Unicos Interacciona' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[usuarios unicos]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 5b37534f-4b54-4370-af2d-efa6da493bb3

	measure 'Usuarios Potenciales' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: f84189d6-7cd3-4cfb-a241-cd6f8f84632a

	measure Visitas = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[visitas]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 381fcaa8-b0f5-4c69-88e9-1dc7d4f47842

	measure 'Paginas Vistas' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[paginas vistas]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: ef9cf958-36e4-49d2-8b76-9eef126ff4a1

	measure 'Tasa de Acceso' = DIVIDE([Usuarios Unicos Interacciona], [Usuarios Potenciales], "No hay datos")
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: f53ee4eb-4bf2-4247-81f3-55260bdb9e79

	measure 'LYTD Paginas Vistas' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[paginas vistas]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 5e5ca97f-b4a2-422d-8f60-253da169301b

	measure 'LYTD Usuarios Potenciales' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 9b3cdc93-62ae-491e-99c6-71f8545aab49

	measure 'LYTD Usuarios Unicos' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[usuarios unicos]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 9eb9238b-1d58-4f8e-ac7b-2559f4f02494

	measure 'LYTD Visitas' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Hecho[visitas]),
			    FILTER(
			        'Interacciona_Accesos_Hecho',
			        'Interacciona_Accesos_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 0df5985b-a19c-4b29-b6d0-7d04f09b826e

	measure 'LYTD Tasa de Acceso' = DIVIDE([LYTD Usuarios Unicos], [LYTD Usuarios Potenciales], "NaN")
		formatString: #,0.00
		lineageTag: eea4d336-8afc-41b8-8c91-4b2f7309018d

	measure 'Visitas Seccion por Epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Visitas_Seccion_Hecho[Views]),
			    FILTER(
			        'Interacciona_Visitas_Seccion_Hecho',
			        'Interacciona_Visitas_Seccion_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Visitas_Seccion_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Visitas_Seccion_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Visitas_Seccion_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: 7280431a-b5c1-43c4-9613-4508dc11500c

	measure 'Usuarios Unicos Seccion por Epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Visitas_Seccion_Hecho[Unique Users]),
			    FILTER(
			        'Interacciona_Visitas_Seccion_Hecho',
			        'Interacciona_Visitas_Seccion_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Visitas_Seccion_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Visitas_Seccion_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Visitas_Seccion_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: 6be23a09-9466-4cf3-a2c7-fe666378c1db

	measure 'Proporcion Usuarios Unicos Por Seccion' = [Usuarios Unicos Seccion por Epoca]/[Usuarios Unicos Interacciona]
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 2daf0310-ae54-4035-a915-1162a4006b90

	measure 'Distinct Count Noticias Visitadas Inter by epoca' = ```
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Tabla = 
			SUMMARIZE(
			    'interacciona_Noticias_Hecho', 
			    'interacciona_Noticias_Hecho'[interacciona_noticia_hecho_id],
			    'interacciona_Noticias_Hecho'[Tipo Epoca],
			    'interacciona_Noticias_Hecho'[Año],
			    'interacciona_Noticias_Hecho'[Mes],
			    'interacciona_Noticias_Hecho'[Semestre],
			    "FLG",
			
			        IF(
			            TipoEpoca = "Anual" &&
			            'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			            'interacciona_Noticias_Hecho'[Año] = AnoEpoca,
			            TRUE(),
			            IF(
			                TipoEpoca = "Mensual" &&
			                'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			                'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			                'interacciona_Noticias_Hecho'[Mes] = Subepoca,
			                TRUE(),
			                IF(
			                    TipoEpoca = "Semestral" &&
			                    'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			                    'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			                    'interacciona_Noticias_Hecho'[Semestre] = Subepoca,
			                    TRUE(),
			                    FALSE()
			                )
			            )
			        )
			    
			)
			
			
			VAR Tabla_filtrada = FILTER(Tabla, [FLG])
			
			VAR Filtro = FILTER('interacciona_Noticias_Hecho', 'interacciona_Noticias_Hecho'[interacciona_noticia_hecho_id] IN DISTINCT(SELECTCOLUMNS(Tabla_filtrada, "interacciona_noticia_hecho_id", [interacciona_noticia_hecho_id])))
			
			VAR Calculo = CALCULATE(DISTINCTCOUNT('interacciona_Noticias_Hecho'[interacciona_noticia_hecho_id]), Filtro)
			
			return IF(ISBLANK(Calculo),0,Calculo)
			```
		formatString: #,0
		lineageTag: 9400ac2b-704d-44e1-ad8d-9e23cfee2bca

	measure 'Visitas noticias Interacicona By Epoca' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(interacciona_Noticias_Hecho[Visitas]),
			    // ALLSELECTED(interacciona_Noticias_Hecho),
			    FILTER(
			        ALLSELECTED('interacciona_Noticias_Hecho'),
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    )
			
			
			
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 7ce93a6f-77c5-4ec9-9788-d9ac139acb1c

	measure 'Usuarios Unicos noticias Interacicona By Epoca' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(interacciona_Noticias_Hecho[Usuarios Unicos]),
			    ALL(),
			    FILTER(
			        ALL('interacciona_Noticias_Hecho'),
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: c1e25802-a103-43b3-98a6-692f5d399799

	measure 'LYTD Visitas noticias Interacicona By Epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR _max1 = MAXX(ALLSELECTED('Date_DIM'), [Date])
			VAR _max = DATE(YEAR(_max1) - 1, MONTH(_max1), DAY(_max1))
			VAR _min1 = MINX(ALLSELECTED('Date_DIM'), [Date])
			VAR _min = DATE(YEAR(_min1) - 1, MONTH(_min1), DAY(_min1))
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Noticias_Hecho[Visitas]),
			    //ALL(),
			    FILTER(ALL(Date_DIM), Date_DIM[Date]<= _max && Date_DIM[Date]>=_min),
			
			    FILTER(
			        ALL('interacciona_Noticias_Hecho'),
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    ))
			
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: eb04ae62-46cf-41fa-a97a-1e6c6d71edc3

	measure 'LYTD Distinct Count Noticias Visitadas Inter by epoca' = ```
			
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Tabla = 
			SUMMARIZE(
			    'interacciona_Noticias_Hecho', 
			    'interacciona_Noticias_Hecho'[interacciona_noticia_hecho_id],
			    'interacciona_Noticias_Hecho'[Tipo Epoca],
			    'interacciona_Noticias_Hecho'[Año],
			    'interacciona_Noticias_Hecho'[Mes],
			    'interacciona_Noticias_Hecho'[Semestre],
			    "FLG",
			
			        IF(
			            TipoEpoca = "Anual" &&
			            'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			            'interacciona_Noticias_Hecho'[Año] = AnoEpoca,
			            TRUE(),
			            IF(
			                TipoEpoca = "Mensual" &&
			                'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			                'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			                'interacciona_Noticias_Hecho'[Mes] = Subepoca,
			                TRUE(),
			                IF(
			                    TipoEpoca = "Semestral" &&
			                    'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			                    'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			                    'interacciona_Noticias_Hecho'[Semestre] = Subepoca,
			                    TRUE(),
			                    FALSE()
			                )
			            )
			        )
			    
			)
			
			VAR Tabla_filtrada = FILTER(Tabla, [FLG])
			
			VAR Filtro = FILTER('interacciona_Noticias_Hecho', 'interacciona_Noticias_Hecho'[interacciona_noticia_hecho_id] IN DISTINCT(SELECTCOLUMNS(Tabla_filtrada, "interacciona_noticia_hecho_id", [interacciona_noticia_hecho_id])))
			
			VAR Calculo = CALCULATE(DISTINCTCOUNT('interacciona_Noticias_Hecho'[interacciona_noticia_hecho_id]), Filtro)
			
			return IF(ISBLANK(Calculo),0,Calculo)
			```
		formatString: #,0
		lineageTag: 0ca8e195-dcca-40cf-b6fa-54d8ec67f964

	measure 'Noticias Publicadas Inter' = DISTINCTCOUNT(Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id])
		formatString: #,0
		lineageTag: 59c86c02-508b-40f1-aa54-81603dd6918c

	measure 'LYTD Noticias Publicadas Inter' = ```
			
			
			var _max1 =maxx(allselected('Date_DIM'),[Date])
			var _max = date(year(_max1)-1,month(_max1),day(_max1))
			var _min1 =minx(allselected('Date_DIM'),[Date])
			var _min = date(year(_min1)-1,month(_min1),day(_min1))
			return
			CALCULATE(DISTINCTCOUNT(Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id]),filter(all('Date_DIM'),'Date_DIM'[Date]<=_max && 'Date_DIM'[Date]>=_min))
			
			```
		formatString: #,0
		lineageTag: f492b1c1-25cc-4906-b8f7-945aef0b4cdf

	measure 'Distinct Count Noticias Optimizado by epoca' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    DISTINCTCOUNT(interacciona_Noticias_Hecho[interacciona_noticia_id]),
			    FILTER(
			        'interacciona_Noticias_Hecho',
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: a7eda952-e23c-4f18-bd74-2a4a6e77aeed

	measure 'Comparision Usuarios Unicos Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Usuarios Unicos]
			VAR numerator = medidas_Interacciona[Usuarios Unicos Interacciona]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 15428065-3c12-427d-8afd-1af87ec0c011

	measure 'Comparision Usuarios Potenciales Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Usuarios Potenciales]
			VAR numerator = medidas_Interacciona[Usuarios Potenciales]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 637ae97d-1844-4495-83af-ec3e13b862a4

	measure 'Comparision tasa Acceso Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Tasa de Acceso]
			VAR numerator = medidas_Interacciona[Tasa de Acceso]
			VAR difference = IF(ISBLANK(denominator) || denominator = 0 || NOT(ISNUMBER(numerator)) || NOT(ISNUMBER(denominator)), "NaN", DIVIDE(numerator, denominator) - 1)
			
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: cea84fdc-769e-4f9b-859b-2bb6fd405cf5

	measure 'Comparision Visitas Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Visitas]
			VAR numerator = medidas_Interacciona[Visitas]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 60dd584c-b3cf-4fd0-8bce-927fa6c32478

	measure 'Comparision Paginas Vistas Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Paginas Vistas]
			VAR numerator = medidas_Interacciona[Paginas Vistas]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 53082ffb-6c1a-49d0-997f-6b2da7099b5e

	measure 'Comparision Publicacion Noticias Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Noticias Publicadas Inter]
			VAR numerator = medidas_Interacciona[Noticias Publicadas Inter]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 99b1268a-8a67-40f2-bd2e-bd1afb6224dd

	measure 'Comparision Vistas noticias Interacciona' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Visitas noticias Interacicona totales By Epoca]
			VAR numerator = medidas_Interacciona[Visitas noticias Interacicona Totales By Epoca]
			VAR difference = IF(ISBLANK(denominator) || denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		lineageTag: 94d27004-7902-439e-8185-ca2ab045509a

	measure 'Usuarios Unicos Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Visitas_Seccion_Pais_Hecho[Unique Users]),
			    FILTER(
			        'Interacciona_Visitas_Seccion_Pais_Hecho',
			        'Interacciona_Visitas_Seccion_Pais_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Visitas_Seccion_Pais_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Visitas_Seccion_Pais_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Visitas_Seccion_Pais_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 95842f8d-bbec-44f0-8c63-0d3f7efc56d0

	measure 'Visitas Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Visitas_Seccion_Pais_Hecho[Views]),
			    FILTER(
			        'Interacciona_Visitas_Seccion_Pais_Hecho',
			        'Interacciona_Visitas_Seccion_Pais_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Visitas_Seccion_Pais_Hecho'[Año] = AnoEpoca &&
			        
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Visitas_Seccion_Pais_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Visitas_Seccion_Pais_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 47c804b9-36c8-4845-a73c-44906b950da4

	measure 'Usuarios Unicos Accesos Brasil Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: f2d79bf5-4273-410b-87b8-261d8299800f

	measure 'Usuarios Unicos Accesos Australia Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: a4cebb17-1cfd-49cd-8b02-ffc6d3ea69df

	measure 'Usuarios Unicos Accesos Mexico Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 593eeb42-ed41-41ea-8023-12b6f20a3641

	measure 'Usuarios Unicos Accesos Chile Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 28ba9b26-3d55-43d3-8a10-d9e8f21dacd2

	measure 'LYTD Usuarios Unicos Accesos Brasil Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: 0
		displayFolder: Paises
		lineageTag: b7420336-79c4-494f-9011-3b57afe2d5b0

	measure 'LYTD Usuarios Unicos Accesos Australia Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: 0
		displayFolder: Paises
		lineageTag: bc8ad873-8ada-47d6-bc0f-20ae37988d7b

	measure 'LYTD Usuarios Unicos Accesos Mexico Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: 0
		displayFolder: Paises
		lineageTag: b9421d44-537c-4da4-865a-28709d3a635e

	measure 'LYTD Usuarios Unicos Accesos Chile Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios Unicos]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: 0
		displayFolder: Paises
		lineageTag: ab61062f-6bfe-43d1-af80-2a1b3c209ac8

	measure 'Comparision usuarios Unicos Interacciona Australia Paises' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Usuarios Unicos Accesos Australia Interacciona Pais]
			VAR numerator = medidas_Interacciona[Usuarios Unicos Accesos Australia Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 6e283d2c-fa04-4f53-8593-359a28c78451

	measure 'Comparision usuarios Unicos Interacciona Brasil Paises' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Usuarios Unicos Accesos Brasil Interacciona Pais]
			VAR numerator = medidas_Interacciona[Usuarios Unicos Accesos Brasil Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 1c27f894-8b22-4bc7-9349-ea72a38edd92

	measure 'Comparision usuarios Unicos Interacciona Chile Paises' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Usuarios Unicos Accesos Chile Interacciona Pais]
			VAR numerator = medidas_Interacciona[Usuarios Unicos Accesos Chile Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 157dadcb-af37-400a-9b10-e7e8d548d63f

	measure 'Comparision usuarios Unicos Interacciona Mexico Paises' =
			
			
			VAR denominator = medidas_Interacciona[LYTD Usuarios Unicos Accesos Mexico Interacciona Pais]
			VAR numerator = medidas_Interacciona[Usuarios Unicos Accesos Mexico Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 0a60625e-ebe3-4a5c-85d7-667977f76dac

	measure 'Visitas Australia Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 1499298c-a257-4a7a-bc87-aff0aeeb9294

	measure 'Visitas Brasil Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: b1b4e593-00a1-418a-bf86-c0b6be5a85ac

	measure 'Visitas Chile Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 36e2971b-2e33-4b84-9a03-f086e5865a03

	measure 'Visitas Mexico Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 888f0a82-8d62-40dd-b764-5206d337fe24

	measure 'Usuarios Potenciales Mexico Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 3cfd9019-a6a9-4976-9ab7-130dcd5f68ce

	measure 'Usuarios Potenciales Chile Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: fd6a7d20-e768-4473-bfa9-9e16338bbd49

	measure 'Usuarios Potenciales Brasil Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: d0c231d9-efb4-44c1-8417-7b1dc16717b1

	measure 'Usuarios Potenciales Australia Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 431c75fb-2d9c-4088-8a05-027818510510

	measure 'Paginas Vistas Australia Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 2bf3885d-f3a7-4632-abc9-c2fd204627aa

	measure 'Paginas Vistas Brasil Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: fcf3e5b4-0a99-419c-8b29-ad8f3dcfca39

	measure 'Paginas Vistas Chile Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 1f17b2f4-27c7-43f9-89a9-1dc18c980164

	measure 'Paginas Vistas Mexico Interacciona Pais' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		displayFolder: Paises
		lineageTag: 99bcc5c1-1b16-409d-a2c2-3d9071e2d103

	measure 'Comparision Usuarios Potenciales Australia Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Usuarios Potenciales Australia Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 554065cd-6a2c-4184-9e6a-cdc8888eccdb

	measure 'Comparision Usuarios Potenciales Brasil Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Usuarios Potenciales Brasil Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 9a5cfd01-5dd3-4ffb-8a72-e2a02a0fa94e

	measure 'Comparision Usuarios Potenciales Chile Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Usuarios Potenciales Chile Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: c1adcaca-a8b6-4897-b7a9-b48407247253

	measure 'Comparision Usuarios Potenciales Mexico Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Usuarios potenciales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Usuarios Potenciales Mexico Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: ca140311-2037-4bdb-9ad7-f12e11a5f496

	measure 'Comparision Paginas Vistas Australia Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Australia Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 28d10382-4626-4935-9a06-fc5c965c7e56

	measure 'Comparision Paginas Vistas Brasil Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Brasil Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 428d3452-6d60-4853-a380-06456f676008

	measure 'Comparision Paginas Vistas Chile Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Chile Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 6be00087-8819-467b-9e5c-d2b79ae82128

	measure 'Comparision Paginas Vistas Mexico Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Paginas Vistas]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Mexico Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: ffb4b338-a607-4668-b695-18d5221384b2

	measure 'Comparision Visitas Australia Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameAustralia] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Australia Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 76f66e50-4c0e-48e1-9ef6-69e5b96a2404

	measure 'Comparision Visitas Brasil Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameBrasil] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Brasil Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: f3f3bf27-0abe-46d6-8225-d32e11385e93

	measure 'Comparision Visitas Chile Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameChile] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Chile Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: cd6e47d3-c698-41a3-9ba5-3b9d9187e5a7

	measure 'Comparision Visitas Mexico Interacciona Pais' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			VAR denominator = CALCULATE(
			    SUM(Interacciona_Accesos_Paises_Hecho[Visitas totales]),
			    FILTER(
			        'Interacciona_Accesos_Paises_Hecho',
			        'Interacciona_Accesos_Paises_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[Año] = AnoEpoca &&
			        'Interacciona_Accesos_Paises_Hecho'[pais_id] = [NameMexico] &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'Interacciona_Accesos_Paises_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'Interacciona_Accesos_Paises_Hecho'[Semestre] = Subepoca)
			        )
			    )
			)
			
			VAR numerator = medidas_Interacciona[Paginas Vistas Mexico Interacciona Pais]
			VAR difference = IF(ISBLANK(denominator)|| denominator = 0, "NaN", DIVIDE(numerator, denominator) - 1)
			RETURN  IF(difference = "NaN", Comun[Mensaje No Data] & " en " & Comun[Previous Epoca], IF(difference > 0, "+", "") & ROUND(difference * 100, 0) & "% vs " & Comun[Previous Epoca])
		displayFolder: Paises
		lineageTag: 886e7024-b1ff-4dbe-850e-fdae70c33742

	measure NameAustralia = "au y nz"
		displayFolder: Paises
		lineageTag: c081df9b-42d5-48f0-a960-759022e9b3b0

	measure NameMexico = "mx"
		displayFolder: Paises
		lineageTag: 6b7eef2e-c9cf-4ac5-94f9-19d0aa674dc4

	measure NameBrasil = "br"
		displayFolder: Paises
		lineageTag: aa9aea5a-b08a-4562-86aa-7833677c5b89

	measure NameChile = "chile"
		displayFolder: Paises
		lineageTag: 11362f1b-2edc-4649-9c62-1f54871ff33f

	measure 'Visitas noticias Interacicona Totales By Epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(interacciona_Noticias_Hecho[Visitas]),
			    ALLSELECTED(),
			    FILTER(
			        ALL('interacciona_Noticias_Hecho'),
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    )
			    --, REMOVEFILTERS(Date_DIM)
			
			
			
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: ff0ae8da-b97b-4e68-91a9-d45a223fb360

	measure 'LYTD Visitas noticias Interacicona totales By Epoca' =
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca] -1
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR _max1 = MAXX(ALLSELECTED('Date_DIM'), [Date])
			VAR _max = DATE(YEAR(_max1) - 1, MONTH(_max1), DAY(_max1))
			VAR _min1 = MINX(ALLSELECTED('Date_DIM'), [Date])
			VAR _min = DATE(YEAR(_min1) - 1, MONTH(_min1), DAY(_min1))
			
			VAR Calculo =
			CALCULATE(
			    SUM(Interacciona_Noticias_Hecho[Visitas]),
			    //ALL(),
			    FILTER(ALL(Date_DIM), Date_DIM[Date]<= _max && Date_DIM[Date]>=_min),
			
			    FILTER(
			        ALL('interacciona_Noticias_Hecho'),
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    )
			    --, REMOVEFILTERS(Date_DIM)
			    )
			
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
		formatString: #,0
		lineageTag: 4f1a2269-51c8-4c43-ad9d-b459da088644

	measure 'Usuarios Unicos noticias Interacicona By Epoca 2' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			VAR Calculo =
			CALCULATE(
			    SUM(interacciona_Noticias_Hecho[Usuarios Unicos]),
			    //ALL(),
			    FILTER(
			        ALL('interacciona_Noticias_Hecho'),
			        'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			        'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			        (
			            (TipoEpoca = "Anual") ||
			            (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			            (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			        )
			    )
			
			
			
			)
			
			RETURN IF(ISBLANK(Calculo), 0, Calculo)
			
			```
		formatString: #,0
		lineageTag: 692ffd23-5b6b-4a0e-b46a-4ac6c403c18e

	measure 'Visitas noticias Interacicona By Epoca Para publicaciones' = ```
			
			VAR TipoEpoca = Comun[Tipo Epoca]
			VAR AnoEpoca = Comun[Año Epoca]
			VAR Subepoca = Comun[Sub Epoca numero]
			
			
			VAR Calculo =
			CALCULATE(
			    SUMX(
			        VALUES(Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id]),
			        IF(
			            COUNTROWS(FILTER('interacciona_Noticias_Hecho',
			                'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			                'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			                (
			                    (TipoEpoca = "Anual") ||
			                    (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			                    (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			                )
			            )) > 0,
			            calculate(SUM('interacciona_Noticias_Hecho'[Visitas]),
			                FILTER(
			                ALLSELECTED('interacciona_Noticias_Hecho'),
			                'interacciona_Noticias_Hecho'[Tipo Epoca] = TipoEpoca &&
			                'interacciona_Noticias_Hecho'[Año] = AnoEpoca &&
			                (
			                    (TipoEpoca = "Anual") ||
			                    (TipoEpoca = "Mensual" && 'interacciona_Noticias_Hecho'[Mes] = Subepoca) ||
			                    (TipoEpoca = "Semestral" && 'interacciona_Noticias_Hecho'[Semestre] = Subepoca)
			                )
			            ))
			                    ,
			            0
			        )
			    )
			)
			RETURN Calculo
			
			
			```
		formatString: #,0
		lineageTag: 49a50c9e-eef1-4801-bbca-b5b821a535ce

	measure 'Suma visitas 2 periodos' = [LYTD Visitas noticias Interacicona By Epoca]+[Visitas noticias Interacicona By Epoca]
		formatString: 0
		lineageTag: 3f097a28-5539-44c4-81df-c11f96eda906

	partition medidas_Interacciona = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

