table medidas_ranking
	lineageTag: e79acc3f-1543-483d-8d2f-1c6801740529

	measure ranking_email = ```
			
			    var filasTotales = COUNTROWS(All(Campanas_Email_Hecho))
			return
			if(ISBLANK(SUMX(RELATEDTABLE(Campanas_Email_Hecho), [ratio efectividad])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Campanas_Email_Hecho), [ratio efectividad]+ DIVIDE([Helper Rank email],filasTotales*1000) ,
			    SUMX(RELATEDTABLE(Campanas_Email_Hecho), [ratio efectividad]+ DIVIDE([Helper Rank email],filasTotales*1000) )
			))
			```
		formatString: 0
		lineageTag: d525f81e-9897-4e5f-947b-e257d5364776

	measure Rank_interacciona = ```
			
			
			    var filasTotales = COUNTROWS(All(Interacciona_Noticias_Publicacion_Hecho))
			
			    return RANKX(
			        ALLSELECTED(
			        Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id],
			        Interacciona_Noticias_Publicacion_Hecho[REPORT CATEGORY (TOPIC)],
			        Interacciona_Noticias_Publicacion_Hecho[AREA / DIVISION ],
			        Interacciona_Noticias_Publicacion_Hecho[Title ES],
			        Interacciona_Noticias_Publicacion_Hecho[Country],
			        Interacciona_Noticias_Publicacion_Hecho[Publishing Date]
			        
			        ),
			
			        medidas_Interacciona[Visitas noticias Interacicona By Epoca Para publicaciones] + DIVIDE([Helper Rank Interacciona],filasTotales), ,DESC ) 
			
			
			
			
			```
		formatString: 0
		lineageTag: 6be46129-0d8b-4f2c-9ff1-458c39f75633

	measure 'Rank Interacciona_Seccion' = ```
			
			var filasTotales = COUNTROWS(All(Interacciona_Seccion_DIM))
			return 
			if(ISBLANK(SUMX(RELATEDTABLE(Interacciona_Seccion_DIM), [Visitas Seccion por Epoca])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Interacciona_Seccion_DIM[Title]),
			    SUMX(RELATEDTABLE(Interacciona_Seccion_DIM), [Visitas Seccion por Epoca])+ DIVIDE([Helper Rank Interacciona Seccion],filasTotales)) ) 
			    
			
			```
		formatString: 0
		lineageTag: 0c103b3c-8d25-4e2d-bfd0-7326eb7b8f6b

	measure 'Rank Interacciona_Buscador' = ```
			
			    VAR max_Index = MAXX(ALL(Interacciona_Buscador_Hecho), Interacciona_Buscador_Hecho[Index])
			
			    return 
			//     RANKX(
			//         ALLSELECTED(Interacciona_Buscador_Hecho[Term]),
			//         CALCULATE(sum(Interacciona_Buscador_Hecho[Searches]))//+DIVIDE([Helper Rank Interacciona Buscador],filasTotales)       
			    
			// )
			if(ISBLANK(SUMX(RELATEDTABLE(Interacciona_Buscador_Hecho), Interacciona_Buscador_Hecho[Searches])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Interacciona_Buscador_Hecho[term]),
			    CALCULATE(sum(Interacciona_Buscador_Hecho[Searches] )+DIVIDE([Helper Rank Interacciona Buscador],max_Index)
			)))
			```
		formatString: 0
		lineageTag: d88dc5a9-6bea-4f33-baf8-7732997a3b2d

	measure 'Rank InteraccionaTV' = ```
			
			var filasTotales = COUNTROWS(All(InteraccionaTV_Hecho))
			return 
			if(ISBLANK(SUMX(RELATEDTABLE(InteraccionaTV_Hecho), [Views])),
			BLANK(),
			RANKX(
			    ALLSELECTED(InteraccionaTV_Hecho), [Views]+ DIVIDE([Helper Rank Interacciona TV],filasTotales),
			    SUMX(RELATEDTABLE(InteraccionaTV_Hecho), [Views]+ DIVIDE([Helper Rank Interacciona TV],filasTotales))
			))
			
			```
		formatString: 0
		lineageTag: e477f4b6-cead-4f03-aec3-4d13a0ca424d

	measure 'Rank puntos_Encuentro' = ```
			
			 var filasTotales = COUNTROWS(All(Eventos_hecho))
			 RETURN
			if(ISBLANK(SUMX(RELATEDTABLE(Eventos_hecho), [Visualizaciones Unicas Online])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Eventos_hecho), [Visualizaciones Unicas Online] + DIVIDE([Helper Rank Eventos],filasTotales) ,
			    SUMX(RELATEDTABLE(Eventos_hecho), [Visualizaciones Unicas Online] + DIVIDE([Helper Rank Eventos],filasTotales) )
			))
			```
		formatString: 0
		lineageTag: f938fae1-c543-42dd-92dd-debacb38bb3e

	measure 'Rank Encuestas' = ```
			
			var filasTotales = COUNTROWS(All(Encuestas_Hecho))
			return 
			// if(ISBLANK(SUMX(RELATEDTABLE(Encuestas_Hecho), [INVITADOS])),
			// BLANK(),
			RANKX(
			    ALLSELECTED(Encuestas_Hecho), [Nº RESPUESTAS]+ DIVIDE([Helper Rank Encuestas],filasTotales),
			    SUMX(RELATEDTABLE(Encuestas_Hecho), [Nº RESPUESTAS]+ DIVIDE([Helper Rank Encuestas],filasTotales))
			)
			// )
			```
		formatString: 0
		lineageTag: 49cf0fc0-0c7c-4bb4-8373-54ccd88d83b2

	measure 'Rank App_Comunicacions' = ```
			
			var filasTotales = COUNTROWS(All(APP_Campus_Comunicaciones))
			return 
			if(ISBLANK(SUMX(RELATEDTABLE(APP_Campus_Comunicaciones), [N¡ Total Visualizaciones0])),
			BLANK(),
			RANKX(
			    ALLSELECTED(APP_Campus_Comunicaciones[de_categoria_new], APP_Campus_Comunicaciones[de_titulo], APP_Campus_Comunicaciones[flg_habilitar_notificacionespush], APP_Campus_Comunicaciones[fec_publicacion], APP_Campus_Comunicaciones[id_only_contenido] ),
			    SUMX(RELATEDTABLE(APP_Campus_Comunicaciones), [N¡ Total Visualizaciones0]+ DIVIDE([Helper Rank AppCampus Comunicaciones],filasTotales) ) 
			))
			```
		formatString: 0
		lineageTag: 78df032e-76dd-461d-a6c1-184bb9c0e371

	measure 'Rank App_Secciones' = ```
			
			
			    var filasTotales = COUNTROWS(All(App_Campus_Secciones_Agrupadas))
			    return 
			if(ISBLANK(SUMX(RELATEDTABLE(App_Campus_Secciones_Agrupadas), [Visualizaciones Secciones individuales])),
			BLANK(),
			RANKX(
			    ALLSELECTED(App_Campus_Secciones_Agrupadas[Seccion]),
			    calculate(medidas_apps[Visualizaciones Secciones individuales]+divide([Helper Rank App Seccion],filasTotales))
			))
			```
		formatString: 0
		lineageTag: 66b5230a-f089-4801-8348-2da4419b2b45

	measure 'Rank OtrasApps' =
			
			var filasTotales = COUNTROWS(All(Otras_Apps_Hecho))
			return
			if(ISBLANK(SUMX(RELATEDTABLE(Otras_Apps_Hecho), Otras_Apps_Hecho[visitas totales])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Otras_Apps_Hecho),Otras_Apps_Hecho[visitas totales]+ DIVIDE([Helper Rank Otras Apps],filasTotales),
			    SUMX(RELATEDTABLE(Otras_Apps_Hecho), Otras_Apps_Hecho[visitas totales]+ DIVIDE([Helper Rank Otras Apps],filasTotales))
			))
		formatString: 0
		lineageTag: 0fa56d9e-530b-40ac-9119-03c8b87ed5a1

	measure 'Rank Interacciona_Seccion Paises' =
			
			var filasTotales = COUNTROWS(All(Interacciona_Visitas_Seccion_Pais_Hecho))
			RETURN
			if(ISBLANK(SUMX(RELATEDTABLE(Interacciona_Seccion_DIM), medidas_Interacciona[Visitas Interacciona Pais])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Interacciona_Seccion_DIM[Title]), //medidas_Interacciona[Visitas Interacciona Pais]+ DIVIDE([Helper Rank Interacciona Seccion],filasTotales),
			    SUMX(RELATEDTABLE(Interacciona_Seccion_DIM), medidas_Interacciona[Visitas Interacciona Pais])+ DIVIDE([Helper Rank Interacciona Seccion],filasTotales)
			))
			// return filasTotales
		formatString: 0
		lineageTag: e071f931-7118-4c1c-aad5-c21c19979b84

	measure 'Rank Interacciona Todos Países' = ```
			
			    VAR max_Index = MAXX(ALL(Interacciona_Visitas_Seccion_Pais_Hecho), Interacciona_Visitas_Seccion_Pais_Hecho[Index])
			    return 
			    if(ISBLANK(SUMX(RELATEDTABLE(Interacciona_Visitas_Seccion_Pais_Hecho), medidas_Interacciona[Visitas Interacciona Pais])),
			BLANK(),
			RANKX(
			    ALLSELECTED(Interacciona_Visitas_Seccion_Pais_Hecho), medidas_Interacciona[Visitas Interacciona Pais]+DIVIDE([Helper Rank Interacciona Seccion Pais],max_Index),
			    SUMX(RELATEDTABLE(Interacciona_Visitas_Seccion_Pais_Hecho), medidas_Interacciona[Visitas Interacciona Pais]+DIVIDE([Helper Rank Interacciona Seccion Pais],max_Index))
			))
			
			
			
			
			
			
			```
		formatString: 0
		lineageTag: 29aa22a1-8023-45a1-8b16-76866b12f9cc

	measure 'Helper Rank AppCampus Comunicaciones' = ```
			
			    // VAR _curNetwork = SELECTEDVALUE(APP_Campus_Comunicaciones[de_titulo])
			
			    // VAR res = COUNTROWS( FILTER( ALL(APP_Campus_Comunicaciones[de_titulo]), APP_Campus_Comunicaciones[de_titulo] <= _curNetwork ) )
			    // return res
			    VAR _curNetwork = max(APP_Campus_Comunicaciones[Index])
			    return _curNetwork
			
			```
		formatString: 0
		lineageTag: 1f2f1392-b8d5-4e9b-b946-489c1c99c4c6

	measure 'Helper Rank Interacciona' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id])
			
			    VAR res = COUNTROWS( FILTER( ALL(Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id]), Interacciona_Noticias_Publicacion_Hecho[interacciona_noticias_publicacion_hecho_id] <= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: 3a21069d-bb41-4fe4-a094-5e56b4219d3d

	measure 'Helper Rank Interacciona Seccion' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(Interacciona_Seccion_DIM[Title])
			
			    VAR res = COUNTROWS( FILTER( ALL(Interacciona_Seccion_DIM[Title]), Interacciona_Seccion_DIM[Title] <= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: f2adf13b-36f5-4b85-b275-b987c28f97e9

	measure 'Helper Rank Encuestas' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(Encuestas_Hecho[encuesta_hecho_id])
			
			    VAR res = COUNTROWS( FILTER( ALL(Encuestas_Hecho[encuesta_hecho_id]), Encuestas_Hecho[encuesta_hecho_id] <= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: 300689f6-8e11-4a11-89a1-89fcdd9375d3

	measure 'Helper Rank Interacciona Seccion Pais' = ```
			
			    VAR _curNetwork = max(Interacciona_Visitas_Seccion_Pais_Hecho[Index])
			    return _curNetwork
			
			```
		formatString: 0
		lineageTag: c22e6629-7154-4f29-876e-1b2d0633ab72

	measure 'Helper Rank App Seccion' = ```
			
			    /*
			    VAR _curNetwork = SELECTEDVALUE(App_Campus_Secciones_Agrupadas[Seccion])
			
			    VAR res = COUNTROWS( FILTER( ALL(App_Campus_Secciones_Agrupadas[Seccion]), App_Campus_Secciones_Agrupadas[Seccion] <= _curNetwork ) )
			    return res
			    */
			    max(App_Campus_Secciones_Agrupadas[Índice])
			
			```
		formatString: 0
		lineageTag: 95bd4ac2-892c-40f7-96e4-a54e2b002c0e

	measure 'Helper Rank Interacciona Buscador' = ```
			
			    VAR _curNetwork = max(Interacciona_Buscador_Hecho[Index])
			    return _curNetwork
			
			//filasTotales//res_curNetworkmax_Index//
			```
		formatString: 0
		lineageTag: 44bae44a-d35d-4df7-abcf-0462db295b40

	measure 'Helper Rank Interacciona TV' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(InteraccionaTV_Hecho[interaccionaTV_video_id])
			
			    VAR res = COUNTROWS( FILTER( ALL(InteraccionaTV_Hecho[interaccionaTV_video_id]), InteraccionaTV_Hecho[interaccionaTV_video_id] >= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: 1df50e2c-2388-40b3-8004-7c55a63c6681

	measure 'Helper Rank Otras Apps' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(Otras_Apps_Hecho[otras_apps_hecho_id])
			
			    VAR res = COUNTROWS( FILTER( ALL(Otras_Apps_Hecho[otras_apps_hecho_id]), Otras_Apps_Hecho[otras_apps_hecho_id] <= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: a2d6e0bf-59e4-45ae-b4d3-4c20e6bb428d

	measure 'Helper Rank Eventos' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(Eventos_hecho[evento_hecho_id])
			
			    VAR res = COUNTROWS( FILTER( ALL(Eventos_hecho[evento_hecho_id]), Eventos_hecho[evento_hecho_id] <= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: fb722c3f-e136-46f0-83ed-571c12d2cdaa

	measure 'Helper Rank email' = ```
			
			    VAR _curNetwork = SELECTEDVALUE(Campanas_Email_Hecho[campanas_email_hecho_id])
			
			    VAR res = COUNTROWS( FILTER( ALL(Campanas_Email_Hecho[campanas_email_hecho_id]), Campanas_Email_Hecho[campanas_email_hecho_id] <= _curNetwork ) )
			    return res
			```
		formatString: 0
		lineageTag: 40646536-a790-4c4e-9876-71efd9f961b7

	partition medidas_ranking = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

