table Tabla_Navegacion
	lineageTag: d0860b3a-d903-4cf5-8799-543799e82d4a

	measure Navegacion = SELECTEDVALUE('Maestro_Codigos_Pestañas_Categorías'[Categoria])
		lineageTag: 21651fbd-808f-4eef-98c9-780bbd1cb95f

	measure Navegacion_EN = SELECTEDVALUE('Maestro_Codigos_Pestañas_Categorías'[Categoria_EN])
		lineageTag: c6bdc37f-7e4d-4438-9c80-b495217993f1

	partition Tabla_Navegacion = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

